(Gestione risorse)  
Il codice seguente non si comporta bene, dal punto di vista della gestione delle risorse, in presenza  di eccezioni. Individuare almeno un problema, indicando la sequenza di operazioni che porta alla  sua occorrenza. Fornire quindi una soluzione basata sui smart pointer.  
```
void foo() {  
A* a1 = new A(1);  
A* a2 = new A(2);  
job1(a1, a2)  
delete a2;  
A* a3 = new A(3);  
job2(a1, a3)  
job3(a3)  
delete a3;  
delete a1;  
}
```

La sequenza di operazioni che porta all'occorrenza del problema Ã¨ la seguente:

1.  Viene creato un nuovo oggetto di tipo A con "new A(1)".
2.  Viene creato un nuovo oggetto di tipo A con "new A(2)".
3.  Viene chiamata la funzione "job1(a1, a2)".
4.  Se "job1(a1, a2)" l**ancia un'eccezione**, l'esecuzione del codice viene interrotta e salta alla prima istruzione catch che gestisce l'eccezione.
5.  L'istruzione "delete a2" **non viene eseguita,** quindi l'oggetto di tipo A creato con "new A(2)" non viene eliminato.

soluzuione con Idioma RAII:

```
class Resorce_Raii {
private:
int* id_ptr;
Resorce_Raii (cosnt Resorce_Raii& other)
Resorce_Raii& operator=(cosnt Resorce_Raii& other)
public:
Resorce_Raii (int id) :  id_ptr( new int(id)) { }
~Resorce_Raii () { delete id_ptr; }


}
```

```
void foo_Raii() {
Resorce_Raii a1(1);
Resorce_Raii a2(2);
job1(a1, a2) 
Resorce_Raii a3(3);
job2(a1, a3);
job3(a3) ; 
}
```


Soluzione con SMART POINTER
```
Class Resource_ptr {
private:
	std::unique_ptr<int> pi;
public:

Resouce_ptr (const int& x) :pi(new int(x)) {}
~Resouce_ptr() = default;
}
```

```

#include "Resource_ptr.hh"

void foo_ptr() {
Resorce_ptr a1(1);
Resorce_ptr a2(2);
job1(a1, a2) 
Resorce_ptr a3(3);
job2(a1, a3);
job3(a3) ; 
}
```