8)Il seguente codice non ha un comportamento corretto in presenza di eccezioni (nota: si assume che le funzioni lock e unlock facciano la cosa giusta e che la funzione unlock non possa lanciare eccezioni).  
Individuare il problema, indicando la sequenza di operazioni che porta alla sua occorrenza, e  
correggerlo applicando un numero minimo di modifiche al codice. Fornire quindi una soluzione  
alternativa applicando l’idioma “l’acquisizione di risorse e una inizializzazione”.  
````
void f() {  
lock("lock1");  
try {  
lock("lock2");  
try {  
do_the_job();  
unlock("lock2");  
unlock("lock1");  
} catch (...) {  
unlock("lock2");  
}  
} catch (...) {  
unlock("lock1");  
}  
}
````

errore: unlock("lock 1") non viene eseguito in caso di eccezione di do_the_job quindi non viene mai rilasciato. 




CORREZIONE dalla lezione 11:

errore, non è neutrale rispetto alle eccezioni, in caso di errore entra in catch unlock2 ed esce in modalitta normale, senza entrare in catch dell'unlock1, quindi dobbiamo lanciare ``throw``  all'interno dei due catch.

quindi:
````
void f() {  
lock("lock1");  
try {  
lock("lock2");  
try {  
do_the_job();  
unlock("lock2");  
unlock("lock1");  
} catch (...) {  
unlock("lock2"); 
throw; //aggiunto
}  
} catch (...) {  
unlock("lock1");
throw; //aggiunto
}  
}
````

versione RAII:

lock.hh
````
class Lock {
private:
const char*  name_;
public:
explicit Lock (const char* name) :name_(name) {
	lock(name);
}
~Lock() {
	unlock(name_)
}
Lock (const Lock& ) = delete // oppure metto privato c++2005
Lock& operator=(const lock&) = delete //oppure metto privaro c++2005

}
````

f_raii.cc

````
void f_Raii() {  
lock lock1("lock1");  

lock lock2("lock2");  
do_the_job();  


//GLI UNLOCK NON SERVONO PERCHE LE RISORSE VENGONO RILASCIATE NELL DISTRUTTORE
}
